### ISSUE TITLE
Remove ML item from the list

### ISSUE THREAD

**Issue by sailingpalmtree** [balint-gyimesi/balint-gyimesi.github.io#1]
https://github.com/balint-gyimesi/balint-gyimesi.github.io/blob/33a310e764c539867734b02df7849b8efc5eb920/resume/balint_gyimesi_resume.html#L63

**Comment by sailingpalmtree** [comment]
Fixed with commit d6a2a77.

**Comment by balint-gyimesi** [comment]
Commit d6a2a77 fixed it :)
