### ISSUE TITLE
Add comma after "interns"

### ISSUE THREAD

**Issue by seasunlee** [balint-gyimesi/balint-gyimesi.github.io#12]
https://github.com/balint-gyimesi/balint-gyimesi.github.io/blob/7ba385b0a75de7318b111e79c2d05879116e46c1/resume/balint_gyimesi_resume.html#L49

**Comment by sailingpalmtree** [comment]
So, turns out that a comma before the 'and' in a long list is optional. I think I like it without the comma 👍 https://www.grammarly.com/blog/comma-before-and/
