### ISSUE TITLE
change "coached seasoned" to "mentored"

### ISSUE THREAD

**Issue by seasunlee** [balint-gyimesi/balint-gyimesi.github.io#3]
https://github.com/balint-gyimesi/balint-gyimesi.github.io/blob/7ba385b0a75de7318b111e79c2d05879116e46c1/resume/balint_gyimesi_resume.html#L25

**Comment by sailingpalmtree** [comment]
Yeah this is a good point. I used the word 'mentored' later so I was trying to avoid repetition and used 'coached' here instead. Not a big deal, I slightly prefer it this way.
