### ISSUE TITLE
Add comma after "provided guidance"

### ISSUE THREAD

**Issue by seasunlee** [balint-gyimesi/balint-gyimesi.github.io#6]
https://github.com/balint-gyimesi/balint-gyimesi.github.io/blob/7ba385b0a75de7318b111e79c2d05879116e46c1/resume/balint_gyimesi_resume.html#L25

**Comment by sailingpalmtree** [comment]
In this case, the fragment of the sentence makes sense without the comma:
"... provided guidance and technical leadership ..."
